services:
  dockge-website:
    image: php:8.1-apache
    restart: unless-stopped
    ports:
      - 5002:80
    volumes:
      - ./:/var/www/
    command: bash -c "a2enmod rewrite remoteip && apache2-foreground"
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    restart: unless-stopped
x-dockge:
  urls:
    - https://dockge.kuma.pet
networks: {}
