services:
  dockge-website:
    image: php:8.1-apache
    restart: unless-stopped
    ports:
      - 5002:80
    volumes:
      - ./:/var/www/
    command: bash -c "a2enmod rewrite remoteip && apache2-foreground"
